### ISSUE TITLE
Relevance of additional TVS output filtering diode

### ISSUE THREAD

**Issue by invd** [newaetech/chipshouter-picoemp#15]
There is a paper by Toulemont, J., et al. on _"A Simple Protocol to Compare EMFI Platforms."_ which suggests that the ringing/reflection at the coil immediately after a high voltage pulse is a problem and that it can be limited through the use of an inexpensive diode (2020, [IACR preprint](https://eprint.iacr.org/2020/1277.pdf)).

They propose adding an unidirectional Littlefuse `1.5KE600A` transient voltage suppressor (TVS) diode between the voltage generation output and the probe tip to clamp some of the voltage swings.

Based on the tests shown [in the introduction video](https://www.youtube.com/watch?v=nB5arJi-tVE&t=390s), there are not a lot of oscillation cycles for the tested coil on the picoemp, so the main benefit I can see is to reduce the second half-wave of the pulse and maybe reduce the first oscillation after that. However, I'm not sure in if this would result in noticeable benefits during picoemp usage since timing considerations are probably not as important for picoemp users and the second full cycle may not actually inject much voltage into the target.
So the improvement could be to suppress the reverse injection effects of the second half-wave on the target and make the picoemp slightly more targeted/precise? I'm not certain I've gotten the physics right here, so this is very speculative.

The ca. 250V maximum capacitor voltage of the picoemp looks compatible with the min. 570V breakdown voltage safety rating of the mentioned diode, the diode is currently available & low cost, which are some of the reasons I'm considering this. The diode could be located on a small SMA-based filter (as used in the paper) or built directly into custom probe tips (incompatible with higher-voltage glitchers).

@colinoflynn 
You're likely aware of this protection diode concept, what are your thoughts on this? Is it relevant within the typical picoemp pulse behavior and parameters? 
Thanks!

**Comment by colinoflynn** [comment]
Worth a try! FYI the IGBT itself has a "built-in" diode which is why there is no stand-alone one ("built in" but really part of the design of the IGB), so I think where there isn't much cabling between the SMA and coil you won't see that much difference. It would likely make a larger difference if you had a cable between the SMA output and coil. Interestingly with the larger ChipSHOUTER some people use it that way (a SMA cable between the output & the injection tip).

The Toulemont et al paper is using a pulse generator, so it's unclear if it would have this built into the output (depends on the output architecture). Either way if you had cabling from the output to the coil (as they would), I'd expect the diode being present close to the coil to matter more for their use-case.

FYI a better place to discuss (feel free to copy/paste this there) is the https://forum.newae.com area which tracks discussions like this across multiple projects, including ChipSHOUTER users.
